//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yamy_Desktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class caja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public caja()
        {
            this.movimientoCaja = new HashSet<movimientoCaja>();
        }
    
        public int CajaId { get; set; }
        public System.DateTime fechaCaja { get; set; }
        public Nullable<System.DateTime> fechaCierreCaja { get; set; }
        public double montoCaja { get; set; }
        public int SucursalId { get; set; }
    
        public virtual sucursal sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimientoCaja> movimientoCaja { get; set; }
    }
}
