//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yamy_Desktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalleFactura
    {
        public int DetalleFacturaId { get; set; }
        public int cantidad { get; set; }
        public double subtotal { get; set; }
        public double bonificacion { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public int ProductoId { get; set; }
        public string cadenaBusquedaProducto { get; set; }
        public int ComprobanteId { get; set; }
    
        public virtual comprobante comprobante { get; set; }
        public virtual producto producto { get; set; }
    }
}
