//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yamy_Desktop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class baselaymarEntities : DbContext
    {
        public baselaymarEntities()
            : base("name=baselaymarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<AspNetRoleClaims> AspNetRoleClaims { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<AspNetUserTokens> AspNetUserTokens { get; set; }
        public virtual DbSet<caja> caja { get; set; }
        public virtual DbSet<comprobante> comprobante { get; set; }
        public virtual DbSet<detalleFactura> detalleFactura { get; set; }
        public virtual DbSet<estadoComprobante> estadoComprobante { get; set; }
        public virtual DbSet<medioPago> medioPago { get; set; }
        public virtual DbSet<movimientoCaja> movimientoCaja { get; set; }
        public virtual DbSet<movimientoStock> movimientoStock { get; set; }
        public virtual DbSet<personaJuridica> personaJuridica { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<stock> stock { get; set; }
        public virtual DbSet<sucursal> sucursal { get; set; }
        public virtual DbSet<tipoComprobante> tipoComprobante { get; set; }
        public virtual DbSet<tipoMovimientoCaja> tipoMovimientoCaja { get; set; }
        public virtual DbSet<tipoMovimientoStock> tipoMovimientoStock { get; set; }
        public virtual DbSet<userEntradas> userEntradas { get; set; }
        public virtual DbSet<userSucursal> userSucursal { get; set; }
    }
}
