//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yamy_Desktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personaJuridica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personaJuridica()
        {
            this.comprobante = new HashSet<comprobante>();
            this.producto = new HashSet<producto>();
        }
    
        public int PersonaJuridicaId { get; set; }
        public string cuit { get; set; }
        public string razonSocial { get; set; }
        public string nombreFantasia { get; set; }
        public string direccion1 { get; set; }
        public string direccion2 { get; set; }
        public string numeroTelefono1 { get; set; }
        public string numeroTelefono2 { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public string Discriminator { get; set; }
        public string ClienteId { get; set; }
        public string ProveedorId { get; set; }
        public Nullable<double> porcentajeRentabilidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comprobante> comprobante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto> producto { get; set; }
    }
}
